font:
  normal:
    family: "Bitstream Vera Sans Mono"
    style: Regular

  bold:
    family: "Bitstream Vera Sans Mono"
    style: Bold

  italic:
    family: "Bitstream Vera Sans Mono"
    style: Italic

  bold_italic:
    family: "Bitstream Vera Sans Mono"
    style: Bold Italic

  size: 11
