font:
  normal:
    family: "spleen"
    style: Regular
  bold:
    family: "spleen"
    style: Bold

  italic:
    family: "spleen"
    style: Italic

  bold_italic:
    family: "spleen"
    style: Bold Italic

  size: 12
