syntax on                                        " use syntax highlighting
set background=light                             "
match Error /\s\+$/                              " highlight trailing whitespace
set number                                       " use line numbers
set hlsearch incsearch                           " search settings
set formatoptions=tcqro                          "
set scrolloff=5                                  " keep the cursor near the center of the screen
filetype plugin indent on                        " filetype plugin
set clipboard=unnamedplus                        " use the system clipboard
                                                 " Jump to the last position when reopening a file
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
                                                 " insert template.cpp into new C++ files
autocmd BufNewFile main.cpp read ~/codes/sync/template.cpp | normal ggdd

" from https://vim.fandom.com/wiki/Automatic_insertion_of_C/C%2B%2B_header_gates
function! s:insert_gates()
  let gatename = substitute(toupper(expand("%:t")), "\\.", "_", "g")
  execute "normal! i#ifndef " . gatename
  execute "normal! o#define " . gatename . " "
  execute "normal! Go#endif /* " . gatename . " */"
  normal! kk
endfunction
autocmd BufNewFile *.{h,hpp} call <SID>insert_gates()

" no not clutter my home directory
set undofile undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

set sw=2 sts=2 expandtab
