" color scheme settings
syntax on
set background=dark
colo corvine

set cursorline

" line numbering
set number relativenumber

" disable screen flash
set noerrorbells t_vb=

" sane settings for backspace key
set backspace=indent,eol,start

" enable mouse support
set mouse=a

" terminal title
set title

" persistent undo history
set undofile undodir=~/.cache/vim/undo

" autoindent settings
set smartindent
set autoindent
set expandtab

" show tabs are 8 characters
set tabstop=8
" use 2 spaces for indentation
set softtabstop=2
set shiftwidth=2

set list
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·

" Determines whether to use spaces or tabs on the current buffer.
function TabsOrSpaces()
  let numTabs=len(filter(getbufline(bufname("%"), 1, 250), 'v:val =~ "^\\t"'))
  let numSpaces=len(filter(getbufline(bufname("%"), 1, 250), 'v:val =~ "^ "'))

  if numTabs > numSpaces
    set noexpandtab
  endif
endfunction

autocmd BufReadPost * call TabsOrSpaces()

" Jump to the last position when reopening a file
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" disable viminfo for commit msgs
autocmd FileType gitcommit setlocal nobuflisted

" use 4 tabs for c++
autocmd BufRead,BufNewFile *.cpp set softtabstop=4 shiftwidth=4 cindent
autocmd BufRead,BufNewFile *.cc set softtabstop=4 shiftwidth=4 cindent
autocmd BufRead,BufNewFile *.hpp set softtabstop=4 shiftwidth=4 cindent
autocmd BufRead,BufNewFile *.hh set softtabstop=4 shiftwidth=4 cindent
" use tabs makefiles
autocmd BufRead,BufNewFile Makefile* set noexpandtab

" use 2 spaces for ruby
autocmd BufRead,BufNewFile *.rb set tabstop=2 softtabstop=2 shiftwidth=2
