" colorscheme settings
colo default
syntax on
set background=dark

" search settings
set hlsearch incsearch

" disable screen flash
set noerrorbells t_vb=

" sane settings for backspace key
set backspace=indent,eol,start

" enable mouse support
set mouse=a

" terminal title
set title

" persistent undo history
set undofile undodir=~/.cache/vim/undo

" autoindent settings
set smartindent autoindent expandtab

" show tabs as 8 characters
set tabstop=8

" default to using 4 spaces for indentation
set softtabstop=4 shiftwidth=4 expandtab

" listchars = replace hidden characters with visible ones
" set list listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·

" Jump to the last position when reopening a file
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" disable viminfo for commit msgs
autocmd FileType gitcommit setlocal nobuflisted cc=81 textwidth=80

" use tabs for Makefiles
autocmd BufRead,BufNewFile *Makefile* set noexpandtab tabstop=8 softtabstop=8 shiftwidth=8

" use 2-space indentation for C++
autocmd BufRead,BufNewFile *.cpp set softtabstop=2 shiftwidth=2 cindent expandtab
autocmd BufRead,BufNewFile *.cc set softtabstop=2 shiftwidth=2 cindent expandtab
autocmd BufRead,BufNewFile *.hpp set softtabstop=2 shiftwidth=2 cindent expandtab
autocmd BufRead,BufNewFile *.hh set softtabstop=2 shiftwidth=2 cindent expandtab

" Ruby-specific settings
" use 80-character lines as specified in the community-made 'Ruby Style Guide'
autocmd BufRead,BufNewFile *.rb set tabstop=2 softtabstop=2 shiftwidth=2 nospell cc=81

" use 4-space indentation Python
" use 79-character lines as specified in PEP8
autocmd BufRead,BufNewFile *.py set softtabstop=4 shiftwidth=4 cc=80 textwidth=79

function TabsOrSpaces()
  let numTabs=len(filter(getbufline(bufname("%"), 1, 250), 'v:val =~ "^\\t"'))
  let numSpaces=len(filter(getbufline(bufname("%"), 1, 250), 'v:val =~ "^ "'))

  if numTabs > numSpaces
    set tabstop=8 shiftwidth=8 softtabstop=8 noexpandtab
  endif
endfunction

autocmd BufReadPost * call TabsOrSpaces()

" use system clipboard
set clipboard=unnamedplus
